version: 2
jobs:
  node_4:
    docker:
      - image: mhart/alpine-node:4
  node_6:
    docker:
      - image: mhart/alpine-node:6
  node_8:
    docker:
      - image: mhart/alpine-node:8

  build:
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

workflows:
  version: 2
  build:
    jobs:
      - node_4
      - node_6
      - node_8
      - build
          requires:
            - node_4
            - node_6
            - node_8
